theme = "bogster"

[keys.normal]
backspace = {"t" = ":lsp-restart", "s" = ":lsp-stop"}
F1 = {"n" = ":set soft-wrap.enable false", "N" = ":set soft-wrap.enable true", "t" = ":set smart-tab.enable false", "T" = ":set smart-tab.enable true"}
F2 = {"b" = ":buffer-close", "B" = ":buffer-close!", "a" = ":buffer-close-all", "A" = ":buffer-close-all!"}
F3 = { w = ":sh cargo check 2>&1 || true", e = ":sh cargo test -- --nocapture 2>&1 || true", r = ":sh cargo run 2>&1 || true", t = ":sh cargo test 2>&1 || true", b = ":sh cargo build 2>&1 || true"}
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
scrolloff = 1
scroll-lines = 5
shell = ["zsh", "-c"]
soft-wrap.enable = true
bufferline = "multiple"
line-number = "relative"
cursorline = true

cursor-shape = { "insert" = "bar", "select" = "underline"}

lsp = {display-messages = true}
