# Environment variables
# . "/etc/profiles/per-user/sny/etc/profile.d/hm-session-vars.sh"

# Only source this once
if [[ -z "$__HM_ZSH_SESS_VARS_SOURCED" ]]; then
  export __HM_ZSH_SESS_VARS_SOURCED=1
  
fi

ZSH="/usr/share/oh-my-zsh";
ZSH_CACHE_DIR="/home/sny/.cache/oh-my-zsh";
export EDITOR='emacs'
export DOTNET_CLI_TELEMETRY_OPTOUT=0

export COLORTERM=truecolor
