# Environment variables
# . "/etc/profiles/per-user/sny/etc/profile.d/hm-session-vars.sh"

# Only source this once
if [[ -z "$__HM_ZSH_SESS_VARS_SOURCED" ]]; then
  export __HM_ZSH_SESS_VARS_SOURCED=1
  
fi

ZSH="/usr/share/oh-my-zsh";
ZSH_CACHE_DIR="/home/sny/.cache/oh-my-zsh";
export MANPAGER='nvim +Man!'
export QT_QPA_PLATFORMTHEME=kde
export QT_STYLE_OVERRIDE=gtk2
export QT_FONT_DPI=96
export GTK_THEME=Dracula
